# Generated by Django 5.2.6 on 2025-09-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
